### ISSUE TITLE
可以参考一下shader实现吗

### ISSUE THREAD

**Issue by WHYBBE** [CSGarden/CT.WPF.MagicEffects#8]

**Comment by CSGarden** [comment]
你指的shader的生成嘛，如果是的话，我有在文章里写道使用的是HLSL（High Level Shader Language，高级着色器语言）生成的

**Comment by WHYBBE** [comment]
哈哈我知道是hlsl的，我就是看了你的文章发现了WPF可以用shader，然后在软件里做了一些效果，同时你代码里有几个现成的ps/cs文件效果挺好的就直接拿来用了，但是没有编译前的代码，想参考一下fx或hlsl文件，十分感谢（如果不方便的话也没有关系）
